portfolio_project/accounts/urls.py
from django.urls import path
from .views import (
    RegistUserView, HomeView, UserLoginView,
    UserLogoutView, UserView,delete_user_view,user_information,ExplanationView
)


app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', RegistUserView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user/', UserView.as_view(), name='user'),
    path('logout/', UserLogoutView.as_view(), name='logout'),    
    path('delete_user/', delete_user_view , name='delete_user'),
    path('user_information/', user_information, name='user_information'),
    path('explanation/', ExplanationView.as_view(), name='explanation'),
    
]

portfolio_project/clothes/urls.py
from django.urls import path
from .views import (RegisterOuterView,RegisterInnerView,RegisterPantsView,RegisterShoesView,
                    OuterListView,InnerListView,PantsListView,ShoesListView,CoordinateListView,CoordinateUpdateView,
     create_outer_coordinate,add_outer_coordinate_view,delete_picture,add_favorite_outer_view,create_favorite_outer_coordinate,
     add_favorite_outer_coordinate,favorite_outer_delete_picture,
     inner_delete_picture,create_inner_coordinate_view,add_inner_coordinate,add_favorite_inner,create_favorite_inner_coordinate,
     add_favorite_inner_coordinate,favorite_inner_delete_picture,
     pants_delete_picture,create_pants_coordinate,add_pants_coordinate,
     add_favorite_pants_coordinate,create_favorite_pants_coordinate,add_favorite_pants,favorite_pants_delete_picture,
     coordinate_delete,
     shoes_delete_picture,favorite_shoes_delete_picture,create_shoes_coordinate,add_shoes_coordinate,add_favorite_shoes_view,
     create_favorite_shoes_coordinate,add_favorite_shoes_coordinate,
    
    
 )
from django.conf import settings
from django.conf.urls.static import static


app_name = 'clothes'

urlpatterns = [
    path('register_outer/', RegisterOuterView.as_view(), name='register_outer'),
    path('register_inner/', RegisterInnerView.as_view(), name='register_inner'),
    path('register_pants/', RegisterPantsView.as_view(), name='register_pants'),
    path('register_shoes/', RegisterShoesView.as_view(), name='register_shoes'),
    path('outer_list/', OuterListView.as_view(), name='outer_list'), 
    path('create_outer_coordinate<int:pk>/',create_outer_coordinate, name='create_outer_coordinate'), 
    path('add_outer_coordinate/<int:outer_id>/<int:coordinate_id>/', add_outer_coordinate_view, name='add_outer_coordinate_view'),        
    path('delete_picture/<int:pk>', delete_picture, name='delete_picture'),    
    path('add_favorite_outer<int:pk>/',add_favorite_outer_view , name='add_favorite_outer_view'),    
    path('create_favorite_outer_coordinate<int:pk>/',create_favorite_outer_coordinate, name='create_favorite_outer_coordinate'),         
    path('add_favorite_outer_coordinate<int:outer_id>/<int:coordinate_id>/',add_favorite_outer_coordinate, name='add_favorite_outer_coordinate'),     
    path('favorite_outer_delete_picture/<int:pk>', favorite_outer_delete_picture, name='favorite_outer_delete_picture'),   
    path('inner_list/', InnerListView.as_view(), name='inner_list'), 
    path('inner_delete_picture/<int:pk>', inner_delete_picture, name='inner_delete_picture'),
    path('add_inner_coordinate/<int:inner_id>/<int:coordinate_id>/',add_inner_coordinate, name='add_inner_coordinate'),
    path('add_favorite_inner<int:pk>/',add_favorite_inner, name='add_favorite_inner'),
    path('create_favorite_inner_coordinate<int:pk>/',create_favorite_inner_coordinate, name='create_favorite_inner_coordinate'),
    path('add_favorite_inner_coordinate/<int:inner_id>/<int:coordinate_id>',add_favorite_inner_coordinate, name='add_favorite_inner_coordinate'),
    path('favorite_inner_delete_picture/<int:pk>',favorite_inner_delete_picture, name='favorite_inner_delete_picture'),
    path('pants_list/',PantsListView.as_view(), name='pants_list'),
    path('pants_delete_picture/<int:pk>', pants_delete_picture, name='pants_delete_picture'),    
    path('create_inner_coordinate/<int:pk>',create_inner_coordinate_view , name='create_inner_coordinate_view'),    
    path('create_pants_coordinate/<int:pk>',create_pants_coordinate, name='create_pants_coordinate'), 
    path('add_pants_coordinate/<int:pants_id>/<int:coordinate_id>',add_pants_coordinate, name='add_pants_coordinate'),     
    path('add_favorite_pants<int:pk>/',add_favorite_pants, name='add_favorite_pants'),
    path('create_favorite_pants_coordinate<int:pk>/',create_favorite_pants_coordinate, name='create_favorite_pants_coordinate'),    
    path('add_favorite_pants_coordinate/<int:pants_id>/<int:coordinate_id>',add_favorite_pants_coordinate, name='add_favorite_pants_coordinate'),         
    path('favorite_pants_delete_picture/<int:pk>',favorite_pants_delete_picture, name='favorite_pants_delete_picture'),       
    path('shoes_list/',ShoesListView.as_view(), name='shoes_list'),
    path('shoes_delete_picture/<int:pk>',shoes_delete_picture, name='shoes_delete_picture'),
    path('favorite_shoes_delete_picture/<int:pk>',favorite_shoes_delete_picture, name='favorite_shoes_delete_picture'), 
    path('create_shoes_coordinate/<int:pk>',create_shoes_coordinate, name='create_shoes_coordinate'),      
    path('add_favorite_shoes<int:pk>/',add_favorite_shoes_view, name='add_favorite_shoes'),
    path('add_shoes_coordinate/<int:shoes_id>/<int:coordinate_id>',add_shoes_coordinate, name='add_shoes_coordinate'),         
    path('create_favorite_shoes_coordinate/<int:pk>',create_favorite_shoes_coordinate, name='create_favorite_shoes_coordinate'), 
    path('add_favorite_shoes_coordinate/<int:shoes_id>/<int:coordinate_id>',add_favorite_shoes_coordinate, name='add_favorite_shoes_coordinate'),         
    path('coordinate_list/',CoordinateListView.as_view() , name='coordinate_list'),
    path('coordinate/<int:pk>/delete/',coordinate_delete , name='coordinate_delete'),
    path('coordinate_form/<int:pk>',CoordinateUpdateView.as_view() , name='coordinate_form'),
   
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),    
    path('clothes/', include('clothes.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   </head>
<style>
.gradient {
  width: 100%;
  height: 30px;
  background: linear-gradient(to right, #2af598 0%, #009efd 100%);
}
.navbar {
 background: width: 300px;
  height: 50px;
  
  background: radial-gradient(
    circle 200px at center,
    #57f6fe 0%,
    #30c7ec 50%,
    #46aef7 100%
  );
 
     margin: 0 auto ; /* 追加：水平方向に中央揃えに */
      display: flex; /* 追加：子要素を横並びにするために flex を利用 */
      justify-content: space-evenly; /* 追加：子要素を等間隔に配置 */
     align-items: center;
    }
   .navbar a {
      text-decoration: none;
      color: #fff;
      display: block;
    }

</style>
</head>
   <body>
      <nav class="navbar nabvar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'clothes:register_outer' %}">アイテム登録</a>
        <a class="navbar-brand" href="{% url 'clothes:outer_list' %}">アイテム一覧</a>
        
        <a class="navbar-brand" href="{% url 'clothes:coordinate_list' %}">コーディネイト一覧</a>
        
        {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザ登録</a>
        {% endif %}
      </nav>
      {% block content %}{% endblock %}
   </body>
</html>

portfolio_project/templates/delete_user.html
{% extends 'base.html' %}

{% block content %}

<style>
   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        height: 50vh;
        text-align: center;
    }
    
   .center-both p:not(:last-child) {
        margin-bottom: 50px;
    } 

       .paragraph-container {
        margin-bottom: 20px; /* <p> タグの下に余白を追加 */
    }  

    .form-container {
        margin-bottom: 30px; /* <form> タグの下に余白を追加 */
    }

    a.btn_06 {
	display: block;
	text-align: center;
	vertical-align: middle;
	text-decoration: none;
	width: 200px;
	margin: auto;
	padding: 0.3rem 0.1rem;
	font-weight: bold;
	border-radius: 100vh;
	border-bottom: 7px solid #0686b2;
	background: #27acd9;
	color: #fff;
   transform-origin: center;  
}
a.btn_06:hover {
	margin-top: 6px;
	border-bottom: 1px solid #0686b2;
	color: #fff;
}
</style>

<div class="center-both">
 
    <h2>アカウント削除の確認</h2>
  <p>本当にアカウントを削除しますか？</p>

   <div class="form-container">
  <form method="post"action="{% url 'accounts:delete_user' %}"  >
        {% csrf_token %}
        <input type="submit" value="削除する">
    </form>
    </div>

    <div class="paragraph-container">
    <p><a href="{% url 'accounts:home' %}"class="btn_06">キャンセル</a></p> 
    </div>

</div>


{% endblock %}

portfolio_project/templates/explanation.html
{% extends 'base.html' %}
{% block content %}

<style>

   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        {% comment %} height: 50vh; {% endcomment %}
        text-align: center;
    }

    a.btn_06 {
	display: block;
	text-align: center;
	vertical-align: middle;
	text-decoration: none;
	width: 200px;
	margin: auto;
	padding: 0.3rem 0.1rem;
	font-weight: bold;
	border-radius: 100vh;
	border-bottom: 7px solid #0686b2;
	background: #27acd9;
	color: #fff;
   transform-origin: center;  
}
a.btn_06:hover {
	margin-top: 6px;
	border-bottom: 1px solid #0686b2;
	color: #fff;
}
</style>
<br>

<div class="center-both">

<strong>CoordinateCabinetは自身の洋服の画像を保存してコーディネイトを作成するアプリです。</strong><br>
サイトの説明をさせていただきます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_193418.png"  alt="Outer Image">
アイテム登録を選びます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_194908.png"  alt="Outer Image">
登録するアイテムの写真ファイルを選択します。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_132523.png"  alt="Outer Image">
選んだ写真ファイルを開きます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_132717.png"  alt="Outer Image">
保存します。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_194127.png"  alt="Outer Image">
保存が完了しました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_201833.png"  alt="Outer Image">
保存された画像はアイテム一覧に表示されます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_202056.png"  alt="Outer Image">
保存した画像をお気に入りに追加することができます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_202232.png"  alt="Outer Image">
お気に入りは画面上部に表示されます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_202518.png"  alt="Outer Image">
お気に入りから外すこともできます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-27_095654.png"  alt="Outer Image">
お気に入りから外しました<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_202905.png"  alt="Outer Image">
アイテム一覧の画像を選びコーディネイトをつくることができます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_203134.png"  alt="Outer Image">
コーディネイトを作成しました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-27_095947.png"  alt="Outer Image">
コーディネイト一覧に表示され名称と説明を編集できます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-28_165040.png"  alt="Outer Image">
コーディネイトの名称と説明を入力し更新を押します。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_203749.png"  alt="Outer Image">
更新が成功しました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_204131.png"  alt="Outer Image">
コーディネイトの削除をすることができます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_204316.png"  alt="Outer Image">
コーディネイトを削除しました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_204933.png"  alt="Outer Image">
他のアイテムでコーディネイトを作成している場合。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_204750.png"  alt="Outer Image">
そのコーディネイトに追加することができます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_205141.png"  alt="Outer Image">
アイテムをコーディネイトに追加しました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_205325.png"  alt="Outer Image">
すでにあるコーディネイトに別のアイテムを追加できました。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_205603.png"  alt="Outer Image">
アイテムの画像を削除することができます。<br><br>
<img width="400px" height="300px"  src="{{ MEDIA_URL }}/picture/スクリーンショット_2024-02-26_205730.png"  alt="Outer Image">
アイテムを削除しました。<br><br>
<strong>説明は以上になります！自分だけのコーディネイトをつくりましょう！</strong><br>
<p><a href="{% url 'accounts:home' %}"class="btn_06">ホーム画面に戻る</a></p> 

</div>


{% endblock %}

portfolio_project/templates/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<style>
   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        height: 50vh;
        text-align: center;
    }

  .center-both a {
        margin-top: 50px; /* リンクの上部に余白を追加 */
    }

h1 {
  font-size: 3.4rem;
  font-style: italic;
  letter-spacing: .1em;
  color: #fff;
  text-shadow: -4px 3px 0 #fa4141, -8px 6px 0 #000;
   background: radial-gradient(
    circle 200px at center,
    #57f6fe 0%,
    #30c7ec 50%,
    #46aef7 100%
   );
   width: 100%;
   margin-top: 80px; 
   height: 50vh;
   display: flex;
  align-items: center;
  justify-content: center; 
}

a.btn_06 {
	display: block;
	text-align: center;
	vertical-align: middle;
	text-decoration: none;
	width: 200px;
	margin: auto;
	padding: 0.3rem 0.1rem;
	font-weight: bold;
	border-radius: 100vh;
	border-bottom: 7px solid #0686b2;
	background: #27acd9;
	color: #fff;
   transform-origin: center;  
}
a.btn_06:hover {
	margin-top: 6px;
	border-bottom: 1px solid #0686b2;
	color: #fff;
}


</style>
<div class="linear-gradient">
<div class="center-both">
    <h1>~CoordinateCabinet~</h1>
 <br>
 <br>
 <br>

<a href="{% url 'accounts:explanation' %}"class="btn_06">初めての方へ</a><br><br>
 <a href="{% url 'accounts:user_information' %}"class="btn_06">マイページ</a>
</div>




</div>


{% endblock %}

portfolio_project/templates/logout.html
<!DOCTYPE html>
<html lang="ja">


<head>
<meta charset="UTF-8">
<title>ユーザーフォーム</title>
</head>


<body>
    <h1>ログアウトしました。</h1>
    <p><a href="{% url 'accounts:home' %}">ホームへ戻る</a></p>
</body>


</html>

portfolio_project/templates/regist.html
{% extends 'base.html' %}
{% block content %}

<style>
   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        height: 50vh;
        text-align: center;
    }

   .errorlist {
    color: red; /* エラーメッセージを赤色に設定 */
}

  input {
   padding: 10px;
  margin: 5px;
  border: 1px solid #ccc;
  border-radius: 5px;
  background-color: #f5f5f5;
  }

input:focus, select:focus, textarea:focus {
  border-color: #66afe9;
  box-shadow: 0 0 5px #66afe9;
}

button {
  padding: 10px 15px;
  background-color: #4caf50;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

button:hover {
  background-color: #45a049;
}

  select {
    padding: 8px;
    margin: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }  

form input[type="submit"] {
    padding: 10px 15px;
    background-color: #3498db;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }

  form input[type="submit"]:hover {
    background-color: #2980b9;
  }

</style>

<br><br><br><br>
<div class="center-both">


<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="新規登録">
</form>

</div>

{% endblock %}

portfolio_project/templates/user_information.html
{% extends 'base.html' %}
{% block content %}
<style>
   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        height: 50vh;
        text-align: center;
    }

  .center-both a {
        margin-top: 100px; /* リンクの上部に余白を追加 */
        line-height: 5;
    }

    .center-both p:not(:last-child) {
        margin-bottom: 30px;
    }

  .right-top {
  position: absolute;
  top: 20;
  right: 0;
  }

a.btn_06 {
	display: block;
	text-align: center;
	vertical-align: middle;
	text-decoration: none;
	width: 200px;
	margin: auto;
	padding: 0.3rem 0.1rem;
	font-weight: bold;
	border-radius: 100vh;
	border-bottom: 7px solid #0686b2;
	background: #27acd9;
	color: #fff;
   transform-origin: center;  
}
a.btn_06:hover {
	margin-top: 6px;
	border-bottom: 1px solid #0686b2;
	color: #fff;
}

form input[type="submit"] {
    padding: 10px 15px;
    background-color: #3498db;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }

  form input[type="submit"]:hover {
    background-color: #2980b9;
  }

</style>

<div class="right-top"><a href="{% url 'accounts:delete_user' %}"class="btn_06">アカウントを削除する</a></div>

<div class="center-both">
    <h1>マイページ</h1>

<p>ユーザー名: {{ user_data.username }}</p>
<p>メールアドレス: {{ user_data.email }}</p>


<form action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="ログアウト"class="btn_06">
    </form>


 
</div>





{% endblock %}

portfolio_project/templates/user_login.html
{% extends 'base.html' %}
{% block content %}

<style>
   .center-both {
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
        height: 50vh;
        text-align: center;
    }

  .center-both a {
        margin-top: 50px; /* リンクの上部に余白を追加 */
    }

 .errorlist {
    color: red;
  }

a.btn_06 {
	display: block;
	text-align: center;
	vertical-align: middle;
	text-decoration: none;
	width: 300px;
	margin: auto;
	padding: 0.3rem 0.1rem;
	font-weight: bold;
	border-radius: 100vh;
	border-bottom: 7px solid #0686b2;
	background: #27acd9;
	color: #fff;
   transform-origin: center;  
}
a.btn_06:hover {
	margin-top: 6px;
	border-bottom: 1px solid #0686b2;
	color: #fff;
}

  input {
   padding: 10px;
  margin: 5px;
  border: 1px solid #ccc;
  border-radius: 5px;
  background-color: #f5f5f5;
  }

input:focus, select:focus, textarea:focus {
  border-color: #66afe9;
  box-shadow: 0 0 5px #66afe9;
}

button {
  padding: 10px 15px;
  background-color: #4caf50;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

button:hover {
  background-color: #45a049;
}

  select {
    padding: 8px;
    margin: 5px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }  


form input[type="submit"] {
    padding: 10px 15px;
    background-color: #3498db;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }

  form input[type="submit"]:hover {
    background-color: #2980b9;
  }
   

</style>

<br><br><br><br>
<div class="center-both">



<form method="POST">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="hidden" name="next" value="{{ request.GET.next }}">
   <input type="submit" value="ログイン" >
</form><br><br>
<p>アカウントをお持ちでない方は<a href="{% url 'accounts:regist' %}"class="btn_06">こちらから新規登録できます。</a></p> 


</div>

{% endblock %}