portfolio_project/clothes/urls.py
from django.urls import path
from .views import (RegisterOuterView,RegisterInnerView,RegisterPantsView,RegisterShoesView,
                    OuterListView,InnerListView,PantsListView,ShoesListView,CoordinateListView,CoordinateUpdateView,
     create_outer_coordinate,add_outer_coordinate_view,delete_picture,add_favorite_outer_view,create_favorite_outer_coordinate,
     add_favorite_outer_coordinate,favorite_outer_delete_picture,
     inner_delete_picture,create_inner_coordinate_view,add_inner_coordinate,add_favorite_inner,create_favorite_inner_coordinate,
     add_favorite_inner_coordinate,favorite_inner_delete_picture,
     pants_delete_picture,create_pants_coordinate,add_pants_coordinate,
     add_favorite_pants_coordinate,create_favorite_pants_coordinate,add_favorite_pants,favorite_pants_delete_picture,
     coordinate_delete,
     shoes_delete_picture,favorite_shoes_delete_picture,create_shoes_coordinate,add_shoes_coordinate,add_favorite_shoes_view,
     create_favorite_shoes_coordinate,add_favorite_shoes_coordinate,
    
    
 )
from django.conf import settings
from django.conf.urls.static import static


app_name = 'clothes'

urlpatterns = [
    path('register_outer/', RegisterOuterView.as_view(), name='register_outer'),
    path('register_inner/', RegisterInnerView.as_view(), name='register_inner'),
    path('register_pants/', RegisterPantsView.as_view(), name='register_pants'),
    path('register_shoes/', RegisterShoesView.as_view(), name='register_shoes'),
    path('outer_list/', OuterListView.as_view(), name='outer_list'), 
    path('create_outer_coordinate<int:pk>/',create_outer_coordinate, name='create_outer_coordinate'), 
    path('add_outer_coordinate/<int:outer_id>/<int:coordinate_id>/', add_outer_coordinate_view, name='add_outer_coordinate_view'),        
    path('delete_picture/<int:pk>', delete_picture, name='delete_picture'),    
    path('add_favorite_outer<int:pk>/',add_favorite_outer_view , name='add_favorite_outer_view'),    
    path('create_favorite_outer_coordinate<int:pk>/',create_favorite_outer_coordinate, name='create_favorite_outer_coordinate'),         
    path('add_favorite_outer_coordinate<int:outer_id>/<int:coordinate_id>/',add_favorite_outer_coordinate, name='add_favorite_outer_coordinate'),     
    path('favorite_outer_delete_picture/<int:pk>', favorite_outer_delete_picture, name='favorite_outer_delete_picture'),   
    path('inner_list/', InnerListView.as_view(), name='inner_list'), 
    path('inner_delete_picture/<int:pk>', inner_delete_picture, name='inner_delete_picture'),
    path('add_inner_coordinate/<int:inner_id>/<int:coordinate_id>/',add_inner_coordinate, name='add_inner_coordinate'),
    path('add_favorite_inner<int:pk>/',add_favorite_inner, name='add_favorite_inner'),
    path('create_favorite_inner_coordinate<int:pk>/',create_favorite_inner_coordinate, name='create_favorite_inner_coordinate'),
    path('add_favorite_inner_coordinate/<int:inner_id>/<int:coordinate_id>',add_favorite_inner_coordinate, name='add_favorite_inner_coordinate'),
    path('favorite_inner_delete_picture/<int:pk>',favorite_inner_delete_picture, name='favorite_inner_delete_picture'),
    path('pants_list/',PantsListView.as_view(), name='pants_list'),
    path('pants_delete_picture/<int:pk>', pants_delete_picture, name='pants_delete_picture'),    
    path('create_inner_coordinate/<int:pk>',create_inner_coordinate_view , name='create_inner_coordinate_view'),    
    path('create_pants_coordinate/<int:pk>',create_pants_coordinate, name='create_pants_coordinate'), 
    path('add_pants_coordinate/<int:pants_id>/<int:coordinate_id>',add_pants_coordinate, name='add_pants_coordinate'),     
    path('add_favorite_pants<int:pk>/',add_favorite_pants, name='add_favorite_pants'),
    path('create_favorite_pants_coordinate<int:pk>/',create_favorite_pants_coordinate, name='create_favorite_pants_coordinate'),    
    path('add_favorite_pants_coordinate/<int:pants_id>/<int:coordinate_id>',add_favorite_pants_coordinate, name='add_favorite_pants_coordinate'),         
    path('favorite_pants_delete_picture/<int:pk>',favorite_pants_delete_picture, name='favorite_pants_delete_picture'),       
    path('shoes_list/',ShoesListView.as_view(), name='shoes_list'),
    path('shoes_delete_picture/<int:pk>',shoes_delete_picture, name='shoes_delete_picture'),
    path('favorite_shoes_delete_picture/<int:pk>',favorite_shoes_delete_picture, name='favorite_shoes_delete_picture'), 
    path('create_shoes_coordinate/<int:pk>',create_shoes_coordinate, name='create_shoes_coordinate'),      
    path('add_favorite_shoes<int:pk>/',add_favorite_shoes_view, name='add_favorite_shoes'),
    path('add_shoes_coordinate/<int:shoes_id>/<int:coordinate_id>',add_shoes_coordinate, name='add_shoes_coordinate'),         
    path('create_favorite_shoes_coordinate/<int:pk>',create_favorite_shoes_coordinate, name='create_favorite_shoes_coordinate'), 
    path('add_favorite_shoes_coordinate/<int:shoes_id>/<int:coordinate_id>',add_favorite_shoes_coordinate, name='add_favorite_shoes_coordinate'),         
    path('coordinate_list/',CoordinateListView.as_view() , name='coordinate_list'),
    path('coordinate/<int:pk>/delete/',coordinate_delete , name='coordinate_delete'),
    path('coordinate_form/<int:pk>',CoordinateUpdateView.as_view() , name='coordinate_form'),
   
   

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('accounts.urls')),    
    path('clothes/', include('clothes.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_project/clothes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Outer,Inner,Pants,Shoes,Coordinate,Favorite
from django.views.generic.edit import (
    CreateView, UpdateView, DeleteView,
    FormView,
)
import os
from . import forms
from django.db import models 
from .forms import OuterForm,InnerForm,PantsForm,ShoesForm,CoordinateForm,CoordinateUpdateForm
from datetime import datetime
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from random import choice
from django.db import transaction
from django.http import Http404
from django.core.files.base import ContentFile


class RegisterOuterView(FormView,SuccessMessageMixin):
    template_name = 'clothes/register_outer.html'
    form_class = OuterForm 
    success_url = reverse_lazy('clothes:register_outer')
  
    
    def post(self, request, *args, **kwargs):
        outer_form = OuterForm(request.POST or None, request.FILES or None)
        
        if outer_form.is_valid() and outer_form.files:
            outer_instance = outer_form.save(commit=False)
            outer_instance.create_at = datetime.now()
            outer_instance.update_at = datetime.now()
            outer_instance.user = self.request.user
            outer_instance.save()
            messages.success(request, 'アウターを登録しました')

            return self.form_valid(outer_form)
        
        return super().post(request, *args, **kwargs)
   

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['outer_form'] = OuterForm()
        return context
    
    def form_valid(self, form):
        form.instance.create_at = datetime.now()
        form.instance.update_at = datetime.now()
        form.instance.user = self.request.user
        return super().form_valid(form) 
    
  

class RegisterInnerView(FormView):
    template_name = 'clothes/register_inner.html'
    form_class = InnerForm 
    success_url = reverse_lazy('clothes:register_inner')
    
    def post(self, request, *args, **kwargs):
        inner_form = InnerForm(request.POST or None, request.FILES or None)
        
        if inner_form.is_valid() and inner_form.files:
            inner_instance = inner_form.save(commit=False)
            inner_instance.create_at = datetime.now()
            inner_instance.update_at = datetime.now()
            inner_instance.user = self.request.user
            inner_instance.save()
            messages.success(request, 'インナーを登録しました')

            return self.form_valid(inner_form)

        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inner_form'] = InnerForm()
        return context
    
    def form_valid(self, form):
        form.instance.create_at = datetime.now()
        form.instance.update_at = datetime.now()
        form.instance.user = self.request.user
        return super().form_valid(form) 
    
    
    
class RegisterPantsView(FormView):
    template_name = 'clothes/register_pants.html'
    form_class = PantsForm 
    success_url = reverse_lazy('clothes:register_pants')
    
    def post(self, request, *args, **kwargs):
        pants_form = PantsForm(request.POST or None, request.FILES or None)
        
        if pants_form.is_valid() and pants_form.files:
            pants_instance = pants_form.save(commit=False)
            pants_instance.create_at = datetime.now()
            pants_instance.update_at = datetime.now()
            pants_instance.user = self.request.user
            pants_instance.save()
            messages.success(request, 'パンツを登録しました')

            return self.form_valid(pants_form)

        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pants_form'] = PantsForm()
        return context
    
    def form_valid(self, form):
        form.instance.create_at = datetime.now()
        form.instance.update_at = datetime.now()
        form.instance.user = self.request.user
        return super().form_valid(form) 
    
class RegisterShoesView(FormView):
    template_name = 'clothes/register_shoes.html'
    form_class = ShoesForm 
    success_url = reverse_lazy('clothes:register_shoes')
    
    def post(self, request, *args, **kwargs):
        shoes_form = ShoesForm(request.POST or None, request.FILES or None)
        
        if shoes_form.is_valid() and shoes_form.files:
            shoes_instance = shoes_form.save(commit=False)
            shoes_instance.create_at = datetime.now()
            shoes_instance.update_at = datetime.now()            
            shoes_instance.user = self.request.user
            shoes_instance.save()
            messages.success(request, 'シューズを登録しました')

            return self.form_valid(shoes_form)

        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['shoes_form'] = ShoesForm()
        return context
    
    def form_valid(self, form):
        form.instance.create_at = datetime.now()
        form.instance.update_at = datetime.now()
        form.instance.user = self.request.user
        return super().form_valid(form) 

    
class OuterListView(ListView):
    model = Outer
    model = Coordinate
    model = Favorite
    template_name = 'clothes/outer_list.html'
   
    context_object_name1 = 'outers'
    context_object_name2 = 'coordinates'
    context_object_name3 = 'favorites'

    
    def get_queryset(self):
       if self.request.user.is_authenticated:
         outer_queryset = Outer.objects.filter(user=self.request.user)
         coordinate_queryset = Coordinate.objects.filter(user=self.request.user)
         favorite_queryset = Favorite.objects.filter(user=self.request.user)
         return outer_queryset, coordinate_queryset, favorite_queryset
       else:
        return Outer.objects.none(), Coordinate.objects.none(), Favorite.objects.none()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        outer_queryset, coordinate_queryset, favorite_queryset = self.get_queryset()
        context[self.context_object_name1] = outer_queryset
        context[self.context_object_name2] = coordinate_queryset
        context[self.context_object_name3] = favorite_queryset        
        return context
    
class InnerListView(ListView):
    model = Inner
    model = Coordinate
    model = Favorite
    template_name = 'clothes/inner_list.html'
    context_object_name1 = 'inners'
    context_object_name2 = 'coordinates'
    context_object_name3 = 'favorites'
    
    def get_queryset(self):          
       if self.request.user.is_authenticated:
         inner_queryset = Inner.objects.filter(user=self.request.user)
         coordinate_queryset = Coordinate.objects.filter(user=self.request.user)
         favorite_queryset = Favorite.objects.filter(user=self.request.user)
         return inner_queryset, coordinate_queryset, favorite_queryset
       else:
        return Inner.objects.none(), Coordinate.objects.none(),Favorite.objects.none()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        inner_queryset, coordinate_queryset, favorite_queryset = self.get_queryset()
        context[self.context_object_name1] = inner_queryset
        context[self.context_object_name2] = coordinate_queryset
        context[self.context_object_name3] = favorite_queryset
        return context
    
class PantsListView(ListView):
    model = Pants
    model = Coordinate
    model = Favorite
    template_name = 'clothes/pants_list.html'
   
    context_object_name1 = 'pants'
    context_object_name2 = 'coordinates'
    context_object_name3 = 'favorites'

    
    def get_queryset(self):
       if self.request.user.is_authenticated:
         pants_queryset = Pants.objects.filter(user=self.request.user)
         coordinate_queryset = Coordinate.objects.filter(user=self.request.user)
         favorite_queryset = Favorite.objects.filter(user=self.request.user)
         return pants_queryset, coordinate_queryset, favorite_queryset
       else:
        return Pants.objects.none(), Coordinate.objects.none(), Favorite.objects.none()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        pants_queryset, coordinate_queryset, favorite_queryset = self.get_queryset()
        context[self.context_object_name1] = pants_queryset
        context[self.context_object_name2] = coordinate_queryset
        context[self.context_object_name3] = favorite_queryset        
        return context
    
class CoordinateListView(ListView):
    model = Coordinate
    template_name = 'coordinate_list.html'
    context_object_name = 'coordinates'
    
    def get_queryset(self):
       if self.request.user.is_authenticated:
         coordinate_queryset = Coordinate.objects.filter(user=self.request.user)
         return  coordinate_queryset
       else:
        return Coordinate.objects.none()   
    
class CoordinateUpdateView(SuccessMessageMixin,UpdateView):          
    template_name = 'clothes/coordinate_form.html'
    model = Coordinate
    fields = ['name', 'description']
    success_message = '更新に成功しました'
    success_url = reverse_lazy('clothes:coordinate_list')   
    
def coordinate_delete(request, pk):
    coordinate = get_object_or_404(Coordinate, pk=pk)
    
    with transaction.atomic():
        coordinate.delete()
    

portfolio_project/templates/clothes/coordinate_list.html
{% extends "base.html" %}
{% block content %}
 <html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coordinate List</title>
</head>
<body>

<style>
    .coordinate-list {
        display: flex;
        flex-wrap: wrap; /* 画像が横に並びきれない場合に折り返す */
        list-style: none; /* 箇条書きスタイルを削除 */
        padding: 0;
        
    }

    .coordinate-list li {
        margin-right: 20px; /* 画像間の余白 */
        margin-bottom: 20px; /* 下に余白を追加 */
    }

    .coordinate-list img {
        width: 50px;
        height: 50px;
        margin-bottom: 5px; /* 画像下の余白 */
    }

    .coordinate-actions {
        display: flex;
    }

    .coordinate-actions a {
        margin-right: 10px;
    }

h2 {
  position: relative;
  padding: 1rem .5rem;
}

h2:before,
h2:after {
  position: absolute;
  left: 0;
  width: 100%;
  height: 4px;
  content: '';
}
h2:after {
    bottom: 0;
    background: linear-gradient(to right, #001f3f,#add8e6);
}
h2:before {
  top: 0;
   background: linear-gradient(to right, #001f3f,#add8e6);
}

a.btn-radius-solid {
  background: #f1e767;
  background: -webkit-gradient(linear, left top, left bottom, from(#f1e767), to(#feb645));
  background: -webkit-linear-gradient(top, #f1e767 0%, #feb645 100%);
  background: linear-gradient(to bottom, #f1e767 0%, #feb645 100%);
}

a.btn-radius-solid:hover {
  background: -webkit-gradient(linear, left bottom, left top, from(#f1e767), to(#feb645));
  background: -webkit-linear-gradient(bottom, #f1e767 0%, #feb645 100%);
  background: linear-gradient(to top, #f1e767 0%, #feb645 100%);
}


</style>

{% if messages %}
{% for message in messages %}
  {{ message.message }}
{% endfor %}
{% endif %}

<br>
    <h2>Coordinate List</h2>


    <ul>
    
        {% for coordinate in coordinates %}
            <li>
                <strong>Name:</strong> {{ coordinate.name }}<br>
                <strong>Description:</strong> {{ coordinate.description }}<br>
                <ul class="coordinate-list">
                {% if coordinate.outer %}
                <li><strong>Outer:</strong> <img width="50px" height="50px" src="{{ coordinate.outer.url }}" alt="Outer Image"></li><br>
                {% endif %}      
                {% if coordinate.inner %}
                <li><strong>Inner:</strong> <img width="50px" height="50px" src="{{ coordinate.inner.url }}" alt="Inner Image"></li><br>                
                {% endif %}
                {% if coordinate.pants %}
                <li><strong>Pants:</strong> <img width="50px" height="50px" src="{{ coordinate.pants.url }}" alt="Pants Image"></li><br>                
                {% endif %}               
                {% if coordinate.shoes %}
                <li><strong>Shoes:</strong> <img width="50px" height="50px" src="{{ coordinate.shoes.url }}" alt="Shoes Image"></li><br>                
                {% endif %}             
                 </ul>
                <a href="{% url 'clothes:coordinate_form' pk=coordinate.id %}"class="btn btn-radius-solid btn--shadow">編集<i class="fas fa-angle-right fa-position-right"></i></a> &nbsp; &nbsp; &nbsp; &nbsp;
                <a href="{% url 'clothes:coordinate_delete' pk=coordinate.id %}"class="btn btn-radius-solid btn--shadow">削除<i class="fas fa-angle-right fa-position-right"></i></a>
            </li>
        {% endfor %}
    </ul>
</body>
</html>
{% endblock %}

portfolio_project/templates/clothes/detail.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
{% csrf_token %}

<h2>詳細画面だよ</h2>
<p>{{ object.picture }}を削除しますか？？</P>
<input type="submit" value="削除">

{% endblock %}

portfolio_project/templates/clothes/inner_list.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
{% csrf_token %}
{% if messages %}
{% for message in messages %}
  {{ message.message }}
{% endfor %}
{% endif %}

<style>
h2 {
  position: relative;
  padding: 1rem .5rem;
}

h2:before,
h2:after {
  position: absolute;
  left: 0;
  width: 100%;
  height: 4px;
  content: '';
  background-image: -webkit-gradient(linear, right top, left top, from(#30cfd0), to(#330867));
  background-image: -webkit-linear-gradient(right, #30cfd0 0%, #330867 100%);
  background-image: linear-gradient(to left, #30cfd0 0%, #330867 100%);
}

h2:before {
  top: 0;
}

h2:after {
  bottom: 0;
}


h4 {
  position: relative;
  padding: 1rem 2rem;
  border-bottom: 6px solid #094;
}

h4:after {
  position: absolute;
  bottom: -6px;
  left: 0;
  width: 20%;
  height: 6px;
  content: '';
  background: #00cc5b;
}

 a.btn-radius-solid {
      border: 1px solid #ccc;
      background: #f1e767;
      background: -webkit-gradient(linear, left top, left bottom, from(#fdfbfb), to(#ebedee));
      background: -webkit-linear-gradient(top, #fdfbfb 0%, #ebedee 100%);
      background: linear-gradient(to bottom, #fdfbfb 0%, #ebedee 100%);
      -webkit-box-shadow: inset 1px 1px 1px #fff;
      box-shadow: inset 1px 1px 1px #fff;
      text-decoration: none; /* リンクのデフォルトのアンダーラインを削除 */
    }

    a.btn-radius-solid:hover {
      background: -webkit-gradient(linear, left bottom, left top, from(#fdfbfb), to(#ebedee));
      background: -webkit-linear-gradient(bottom, #fdfbfb 0%, #ebedee 100%);
      background: linear-gradient(to top, #fdfbfb 0%, #ebedee 100%);
    }

.link-container {
    display: flex;
    flex-wrap: wrap; 
    display: flex; /* 追加：子要素を横並びにするために flex を利用 */
      justify-content: center; /* 追加：子要素を等間隔に配置 */
     align-items: center; 
}

.link-item {
      margin-right: 80px; /* リンク間の余白を設定 */
      margin-bottom: 10px;
}

 .link-container a {
        margin-top: 20px; 
        margin-right: 80px; /* リンクの上部に余白を追加 */
       
    } 

   .form-container {
        margin-top: 50px; /* <form> タグの下に余白を追加 */
    }

.custom-hr {
  position: static;
  {% comment %} padding: 1rem 2rem; {% endcomment %}
  height: 5px;
  background: linear-gradient(to right, #00cc5b 40%,  #094 60%);
 
  content: '';

  }

h5 {
  padding: 1rem 3rem;
  color: #fff;
  border-radius: 100vh;
  background-image: -webkit-gradient(linear, right top, left top, from(#9be15d), to(#00e3ae));
  background-image: -webkit-linear-gradient(right, #9be15d 0%, #00e3ae 100%);
  background-image: linear-gradient(to left, #9be15d 0%, #00e3ae 100%);
}

a.btn-gradient {
  -webkit-transform: skew(-15deg);
  transform: skew(-15deg);
  color: #fff;
  border-radius: 0;
  background-image: -webkit-gradient(linear, left top, right top, from(#2af598), to(#009efd));
  background-image: -webkit-linear-gradient(left, #2af598 0%, #009efd 100%);
  background-image: linear-gradient(90deg, #2af598 0%, #009efd 100%);
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, .1);
  box-shadow: 0 5px 10px rgba(0, 0, 0, .1);
}

a.btn-gradient:hover {
  -webkit-transform: skew(0);
  transform: skew(0);
  color: #fff;
  -webkit-box-shadow: 0 2px 3px rgba(0, 0, 0, .1);
  box-shadow: 0 2px 3px rgba(0, 0, 0, .1);
}

</style>
<div class="link-container">
  <a href=" {% url 'clothes:outer_list' %}"class="btn btn-radius-solid">アウターリスト<i class="fas fa-angle-right fa-position-right"></i></a> 
   <a href=" {% url 'clothes:inner_list' %}"class="btn btn-radius-solid">インナーリスト<i class="fas fa-angle-right fa-position-right"></i></a>  
  <a href=" {% url 'clothes:pants_list' %}"class="btn btn-radius-solid">パンツリスト<i class="fas fa-angle-right fa-position-right"></i></a> 
  <a href=" {% url 'clothes:shoes_list' %}"class="btn btn-radius-solid">シューズリスト<i class="fas fa-angle-right fa-position-right"></i></a>
</div>
<br>
<h2>Inner List</h2>
<hr class="custom-hr" >
<h5>お気に入り</h5>

{% for favorite in favorites %}

{% if favorite.inner %} 
<hr>

<img width="100px" height="100px"  src="{{ favorite.inner.url}}" alt="Inner Image">
<a href=" {% url 'clothes:create_favorite_inner_coordinate' pk=favorite.id %}"class="btn btn-gradient">コーディネイトを作成する</a> &nbsp; &nbsp; &nbsp; &nbsp;
{% for coordinate in coordinates %}
{% if not coordinate.inner %}
<a href=" {% url 'clothes:add_favorite_inner_coordinate' inner_id=favorite.id coordinate_id=coordinate.id %}"class="btn btn-gradient">コーディネイト{{ coordinate. }}に追加する</a> &nbsp; &nbsp; &nbsp; &nbsp;
 {% endif %}
{% endfor %}&nbsp; &nbsp; &nbsp; &nbsp;
<a href=" {% url 'clothes:favorite_inner_delete_picture' pk=favorite.id %}"class="btn btn-gradient">お気に入りから外す</a> 
{% endif %}
{% endfor %}

<hr class="custom-hr" >


{% for inner in inners %}
<hr>



 <img width="100px" height="100px"  src="{{ inner.inner.url}}" alt="Inner Image">
  <a href=" {% url 'clothes:add_favorite_inner' pk=inner.id %}"class="btn btn-gradient">お気に入りに追加する</a> &nbsp; &nbsp; &nbsp; &nbsp;
  <a href=" {% url 'clothes:create_inner_coordinate_view' pk=inner.id %}"class="btn btn-gradient">コーディネイトを作成する</a> &nbsp; &nbsp; &nbsp; &nbsp;
{% for coordinate in coordinates %}
{% if not coordinate.inner %}
  <a href=" {% url 'clothes:add_inner_coordinate' inner_id=inner.id coordinate_id=coordinate.id %}"class="btn btn-gradient">コーディネイト{{ coordinate.name }}に追加する</a> &nbsp; &nbsp; &nbsp; &nbsp;
 {% endif %}
{% endfor %}&nbsp; &nbsp; &nbsp; &nbsp;
<a href=" {% url 'clothes:inner_delete_picture' pk=inner.id %}"class="btn btn-gradient">削除する</a> 

{% endfor %}
</tr> 

</form>
{% endblock %}